# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "baruchiro.gitjournal" => "CI - baruchiro.gitjournal",
          "baruchiro.gitjournal.ShareExtension" => "CI - baruchiro.gitjournal.ShareExtension"
        }
      }
    )
    #upload_to_app_store(skip_metadata: true, skip_screenshots: true)
    changelog_from_git_commits
    upload_to_testflight(apple_id:"1466519634", skip_waiting_for_build_processing:true)
  end
end
