# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: Apache-2.0

name: Android

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'

      - name: Set Build Number into env
        run: echo "BUILDNUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV
      - name: build
        run: flutter build apk --flavor dev --debug --build-number="$BUILD_NUM" --dart-define=INSTALL_SOURCE=fdroid
      - name: rename
        run: cp build/app/outputs/flutter-apk/app-dev-debug.apk baruchiro.gitjournal_$BUILD_NUM.apk
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: baruchiro.gitjournal_$BUILD_NUM.apk
          name: $BUILD_NUM
          tag_name: $BUILD_NUM
      # - name: Build
      #   run: ./scripts/build_android.sh
      # - name: "Upload Artifact"
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: APK
      #     path: "*.apk"
      #     if-no-files-found: error
      # - name: Publish Alpha
      #   run: cd android && fastlane alphaBuild
