# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: Apache-2.0

name: Android

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    container: ghcr.io/gitjournal/flutter-android-sdk:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config --global --add safe.directory '*'

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '12'
          cache: gradle
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6' # Set the version of Flutter you want to use

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34' # Set the version of the Android SDK you want to use
          ndk-version: '19.2.5345600' # Set the version of the Android NDK you want to use

      - name: Test
        run: ./scripts/test.sh
      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: Unit Tests ${{ matrix.os }} ${{ matrix.sdk }}
      #     path: test-results.xml
      #     reporter: jest-junit
      # - name: Unlock Secrets
      #   env:
      #     GITCRYPT_KEY: ${{ secrets.GITCRYPT_KEY }}
      #   run: ./scripts/decrypt_secrets.sh
      - name: Setup Env
        run: dart ./scripts/setup_env.dart
      - name: Build
        run: ./scripts/build_android.sh
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: "*.apk"
          if-no-files-found: error
      # - name: Publish Alpha
      #   run: cd android && fastlane alphaBuild
